app:
  host: "http://127.0.0.1"
  port: 9000
backends:
  - name: "primary"
    priority: 1
    address: "http://127.0.0.1:8080"
  - name: "secondary"
    priority: 2
    address: "http://127.0.0.1:8081"
